- octopus-distribution/pom.xml
TeamCity and local builds get different version numbers
> Added version number logic in Maven build script

- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusPackPackageBuildProcess.java
- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusPackPackageRunner.java
- octopus-agent/src/main/resources/META-INF/build-agent-plugin-Octopus.TeamCity.xml
- octopus-common/src/main/java/octopus/teamcity/common/OctopusConstants.java
- octopus-server/src/main/java/octopus/teamcity/server/OctopusPackPackageRunType.java
- octopus-server/src/main/resources/META-INF/build-server-plugin-Octopus.TeamCity.xml
- octopus-server/src/main/resources/buildServerResources/editOctopusPackPackage.jsp
- octopus-server/src/main/resources/buildServerResources/viewOctopusPackPackage.jsp
Added a step to allow `octo pack` separate to pushing to Octopus. This also allows packing of NuGet packages, whereas the existing push step only supports Zip because it's using internal functionality of TeamCity.
Objective is also better support for the new `dotnet octo` workflows around .NET Core builds, on .NET Core only platforms.
Have locally tested both publishing the artifact to the TeamCity feed and also not doing that and using  the Octopus Push step to push the NuPkg to Octopus.
> Octopus Pack step

- README.md
- octopus-server/src/main/java/octopus/teamcity/server/OctopusMetadataBuildStartProcessor.java
The TeamCity code doesn't like nulls in the shared parameters, so omit the parameter rather than try to add a null.
Fixes OctopusDeploy/Issues#5514
> Add null check on VcsRoot

- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusMetadataBuildProcess.java
- octopus-server/src/main/java/octopus/teamcity/server/OctopusMetadataBuildStartProcessor.java
This PR addresses issues when the agent uses a different Url to access the server than the UI does. The value shown in the server's administration page is the value we meant to get, but it isn't what's available in the API we originally called, that is the Url the agent uses to talk to the server.
Fixes OctopusDeploy/Issues#5635
> Pass the server's root Url to the agent

- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusCreateReleaseBuildProcess.java
- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusDeployReleaseBuildProcess.java
- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusPromoteReleaseBuildProcess.java
- octopus-common/src/main/java/octopus/teamcity/common/OctopusConstants.java
- octopus-server/src/main/resources/buildServerResources/editOctopusCreateRelease.jsp
- octopus-server/src/main/resources/buildServerResources/editOctopusDeployRelease.jsp
- octopus-server/src/main/resources/buildServerResources/editOctopusPromoteRelease.jsp
- octopus-server/src/main/resources/buildServerResources/viewOctopusCreateRelease.jsp
- octopus-server/src/main/resources/buildServerResources/viewOctopusDeployRelease.jsp
- octopus-server/src/main/resources/buildServerResources/viewOctopusPromoteRelease.jsp
Add these as options to make it easy for users to discover and use these settings. No specific validation has been included, the options only get used when they are relevant, and not seeing a need to be forceful in not have them set or anything like that when they aren't relevant.
Relates to OctopusDeploy/Issues#5388
> Include the Deployment Timeout and Cancel On Timeout options

- octopus-agent/assembly.xml
- octopus-distribution/assembly.xml
This PR includes the gson jar file in the distribution for the TeamCity server and agent packages.
Fixes #21
> Include the gson file in the packages for server and agent

- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusDeployReleaseBuildProcess.java
- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusPromoteReleaseBuildProcess.java
Fixes the NPE described in issue #25, but two other locations not touched by PR #27.
```
java.lang.NullPointerException
at octopus.teamcity.agent.OctopusDeployReleaseBuildProcess$1.buildCommand(OctopusDeployReleaseBuildProcess.java:99)
at octopus.teamcity.agent.OctopusCommandBuilder.buildMaskedCommand(OctopusCommandBuilder.java:32)
at octopus.teamcity.agent.OctopusBuildProcess.startOcto(OctopusBuildProcess.java:87)
at octopus.teamcity.agent.OctopusBuildProcess.start(OctopusBuildProcess.java:54)
at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:61)
at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor …
```
> Fix NPE from #25 in another location.

- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java
- octopus-server/src/main/resources/buildServerResources/editOctopusBuildInformation.jsp
- octopus-server/src/main/resources/buildServerResources/editOctopusCreateRelease.jsp
- octopus-server/src/main/resources/buildServerResources/editOctopusPackPackage.jsp
- octopus-server/src/main/resources/buildServerResources/editOctopusPushPackage.jsp
The build information plugin option does not currently allow for passing command line arguments. This PR adds a block of jsp `editBuildInformation` to allow passing additional command line args and updates the `BuildInformationBuildProcess` to add these arguments to the collected commands.
Additionally, this PR also makes each plugin option consistent with respect to the `Additional command line arguments:` under the 'Advanced' settings group.
Example result from this change:
(Note the --proxy argument now appears in the cli call)
> Add additional cli arguments to build information

- gradle/versions.gradle
- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java
It appears the teamcity-rest-client versioning got reset in ~2017, and the version currently used is the highest number, but is actually quite old.
It has been updated to be 1.14.0.
This upgrade brings in many up-issues to its dependencies which _may_ resolve some outstanding issues around TLSV2.
> Update to latest version of teamcity-rest-client

- build.gradle
- octopus-agent/src/test/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcessTest.java
- octopus-server/src/test/java/octopus/teamcity/server/generic/OctopusBuildStepPropertiesProcessorTest.java
A bug in the topmsot build.gradle meant tests weren't being executed from the commandline.
This has been rectified, and failing tests updated.
> Update build to run tests

- e2e/src/test/java/octopus/teamcity/e2e/dsl/TeamCityFactory.java
- octopus-server/src/main/java/octopus/teamcity/server/OctopusGenericRunType.java
- octopus-server/src/main/resources/META-INF/build-server-plugin-Octopus.TeamCity.xml
- octopus-server/src/main/resources/buildServerResources/viewOctopusPackPackage.jsp
The OctopusGenericStep has been feature-flagged, such that it will not
appear in a TeamCity instance unless the octopus.enable.step.vnext
system property contains the literal text 'true' in the Teamcity
Server.
This can be done by appending "-Doctopus.enable.step.vnext=true" to the
TEAMCITY_SERVER_OPTS environment variable prior to starting the Teamcity
Server.
> Allow the Step Vnext to be feature flagged

- e2e/src/test/java/octopus/teamcity/e2e/test/BuildInformationEndToEndTest.java
The time check used to determine if a build had finished within a a given time limit had logic inverted, such that the test would run forever.
This changeset resolves the issue by switching start/end times on the duration calculation.
> Force BuildInfo AcceptanceTest to timeout

- .github/workflows/release.yml
- build.gradle
Added a github action which, when a release is created, creates a release in the Octopus server for the built package.
The github action can also be run manually - however a link to the Github release must be supplied.
> Github action to create release in OctopusDeploy

- gradle/versions.gradle
- octopus-common/src/main/java/octopus/teamcity/common/connection/ConnectionPropertyNames.java
- octopus-common/src/main/java/octopus/teamcity/common/connection/ConnectionUserData.java
- octopus-server/build.gradle
- octopus-server/src/main/java/octopus/teamcity/server/connection/ConnectionHelper.java
- octopus-server/src/main/java/octopus/teamcity/server/connection/OctopusConnection.java
- octopus-server/src/main/java/octopus/teamcity/server/connection/OctopusConnectionPropertiesProcessor.java
- octopus-server/src/main/java/octopus/teamcity/server/connection/OctopusConnectionsBean.java
- octopus-server/src/main/resources/META-INF/build-server-plugin-Octopus.TeamCity.xml
- octopus-server/src/main/resources/buildServerResources/editOctopusConnection.jsp
This creates an Octopus Server connection, which appears under the connections menu of a teamcity project.
This server is not used in any other feature, but lays the groundwork for future work (re-using said connection in build steps).
> Introduce Octopus Server connection, not yet used

- e2e/src/test/java/octopus/teamcity/e2e/test/BuildInformationEndToEndTest.java
- gradle/versions.gradle
- octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/BaseBuildVcsData.java
- octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/BuildVcsData.java
- octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcess.java
- octopus-agent/src/main/java/octopus/teamcity/agent/generic/OctopusGenericRunner.java
- octopus-agent/src/main/java/octopus/teamcity/agent/pushpackage/OctopusPushPackageBuildProcess.java
- octopus-agent/src/test/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcessTest.java
- octopus-agent/src/test/java/octopus/teamcity/agent/pushpackage/OctopusPushPackageBuildProcessTest.java
This update necessitated a significant update to package and class naming, but functionality remains unchanged.
> Update to SDK 2.0

- .github/workflows/release.yml
When passing multi-line variables between steps, the EOL charcters need to be appropriately mapped - otherwise only the first line is passed - resulting in the current, unexpected behaviour.
This change replaces \r\n characters awith appropriate hex-values.
> Trying to fix the issues with release notes

- octopus-server/src/main/java/octopus/teamcity/server/OctopusBuildInformationBuildStartProcessor.java
Not all builds have an associated User (eg scheduled build)- and therefore cannot necessarily find permissable projects.
This ensures the connections are only added to builds if the StepVNext feature flag is enabled.
Note: if said flag is enabled - the scheduled builds will fail.
> Only attach ConnectionData to build when Vnext enabled

- gradle/versions.gradle
This updates the SDK to version 0.0.4 which ensures
it too is using 2.16.0 of log4j
> Update for log4j to 2.16.0

- gradle.properties
Update log4j to 2.16.0 and Java Client (SDK) to 0.0.4, to mitigate DOS vulnerability, documented:
https://www.zdnet.com/article/second-log4j-vulnerability-found-apache-log4j-2-16-0-released/
> Prepare for 6.1.8 release

- .gitattributes
- build.gradle
- gradle.properties
- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java
- octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuilder.java
- octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcess.java
- octopus-agent/src/test/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcessTest.java
- octopus-server/src/main/java/octopus/teamcity/server/OctopusBuildInformationBuildStartProcessor.java
The Build Information is currently being populated with a BuildUrl that is based on the agent's understanding of the TeamCity server's Url. Unfortunately this is not always the same Url you need in order to view the build in the UI, which is why Octopus wants it, to provide a link back to the build page.
This had previously been using the value from the `Administration -> Global Settings -> Server URL` setting, which is what this PR reverts the code back to using.
Fixes #139
> Fixed an issue with the BuildURL value in the Build Information

- octopus-server/src/main/resources/buildServerResources/editOctopusCreateRelease.jsp
Fixes https://github.com/OctopusDeploy/Issues/issues/7508
The help text incorrectly saying that the value would be ignored if the project is not in Git. This is incorrect. The value must be left blank if the project is not in Git.
> Fix help text for GitRef and Git Commit release creation fields

- .gitattributes
The gitattributes needed to explicitly call out the binaries that we have embedded in the repo
> fixed git attributes

- .github/workflows/main.yml
Rather than faf about with key rotations, use OICD auth
> Use new Octopus OICD auth for pushing TC artifacts during build
